apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.fullname" . }}-sever-headless
  labels:
    app.kubernetes.io/component: zookeeper
{{ include "zookeeper.labels" . | indent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.serverPort }}
      protocol: TCP
      name: sever
    - port: {{ .Values.leaderElectionPort}}
      protocal: TCP
      name: leader-election
  selector:
    app.kubernetes.io/name: {{ include "zookeeper.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: zookeeper
