apiVersion: v1
kind: Service
metadata:
  name: {{ include "zookeeper.fullname" . }}-client
  labels:
{{ include "zookeeper.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.clientPort }}
      protocol: TCP
      name: client
  selector:
    app.kubernetes.io/name: {{ include "zookeeper.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
